MyApp/MyApp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_app/', include('my_app.urls')),
]

MyApp/my_app/urls.py
from django.urls import path, include

from . import views

app_name = 'my_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:user_id>/', views.detail, name='detail'),
    path('create_user/', views.create_user, name='create_user'),
    path('accounts/', include('django.contrib.auth.urls')),
]

MyApp/my_app/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.


class UserManager(models.Manager):
    def create_user(self, f_name, l_name, email, password):
        user = self.create(first_name=f_name, last_name=l_name, email=email, password=password)
        return user


class User(models.Model):
    def __str__(self):
        return self.first_name + ' ' + self.last_name

    first_name = models.CharField(max_length=30, blank=False)
    last_name = models.CharField(max_length=30, blank=False)
    email = models.CharField(max_length=40, blank=False, unique=True)
    password = models.CharField(max_length=150, blank=False)

    objects = UserManager()

MyApp/my_app/forms.py
from django.forms import ModelForm
from .models import User


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = '__all__'

MyApp/my_app/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.db import Error
from django.http import Http404
from django.http import HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from .forms import UserForm
from .models import User

# Create your views here.


def index(request):
    user_list = User.objects.all()
    context = {'user_list': user_list,}
    #output = ', '.join([str(u) for u in user_list])
    return render(request, 'my_app/index.html', context)


def detail(request, user_id):
    try:
        user = User.objects.get(pk=user_id)
    except User.DoesNotExist:
        return Http404("The user with id %s does not exist" % user_id)
    # user = get_object_or_404(User, pk=user_id)
    return render(request, 'my_app/detail.html',
                  {'user': user})


def create_user(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('my_app:index'))
        else:
            return HttpResponseBadRequest("Unable to create a new user.")
    else:
        form = UserForm()
        return render(request, 'my_app/create_user.html',
                      {
                          'form': form
                      })

def update_user(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST)

MyApp/my_app/templates/my_app/create_user.html
<h1>Create a new user</h1>
<form action="{% url 'my_app:create_user' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add user" />
</form>

MyApp/my_app/templates/my_app/detail.html
<h1>User's details</h1>
<p>
    UID : {{ user.id }}<br>
    Name : {{ user }}<br>
    Email : {{ user.email }}<br>
</p>

MyApp/my_app/templates/my_app/index.html
<h1>Users' list</h1>
{% if user_list %}
    <ul>
        {% for user in user_list %}
            <li><a href="{% url 'my_app:detail' user.id %}"> {{ user }} </a></li>
        {% endfor %}
    </ul>
{% else %}
    <p> Hello FUCKERS no users </p>
{% endif %}

MyApp/my_app/templates/my_app/update_user.html
<h1>Update an existing user</h1>
<form action="{% url 'my_app:update_user' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Modify changes" />
</form>